### ISSUE TITLE
Older Browsers Immune?

### ISSUE THREAD

**Issue by optimiz** [jbtronics/CrookedStyleSheets#11]
Hello, neat CSS trick; it works great on newer browsers that support the CSS methods used.  Older browser versions — I tested Firefox v50 and Opera v12 — respond to font tracking only, no other results show; other than that, the CSS on the test page works as expected; i.e., color changes appropriately, etc.

So this is not really a bug…but may be helpful as a mitigation method under the README's prevention section?

**Comment by jbtronics** [comment]
Opera 12 is really very old and I don't think it would be a good suggestion to use it today, because it will contain more security issues than modern browsers...
Also many modern pages don't work really well on opera 12...
I don't think it is worth to tolerate critical bugs in an old browser, only because CSS tracking maybe does not work in them...

**Comment by optimiz** [comment]
No argument here.  Setting browser security aside, I realize it would be silly to pretend to be invisible to tracking when one visits with a unique User Agent like Opera v12 (c. 2013); complete and full tracking mitigation requires a broader approach.  Firefox v50 (c. 2016) is less unique in that regard, but becomes more so each passing year.

Thank you for the good works.
